FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TrackMyMacros.App4/TrackMyMacros.App4.csproj", "TrackMyMacros.App4/"]
COPY ["TrackMyMacros.Dtos/TrackMyMacros.Dtos.csproj", "TrackMyMacros.Dtos/"]
COPY ["TrackMyMacros.Infrastructure/TrackMyMacros.Infrastructure.csproj", "TrackMyMacros.Infrastructure/"]
RUN dotnet restore "TrackMyMacros.App4/TrackMyMacros.App4.csproj"
COPY . .
WORKDIR "/src/TrackMyMacros.App4"
RUN dotnet build "TrackMyMacros.App4.csproj" -c Release -o /app/build

FROM build AS publish
WORKDIR "/src/TrackMyMacros.App4"
RUN dotnet publish "TrackMyMacros.App4.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY TrackMyMacros.App4/nginx.conf /etc/nginx/nginx.conf
