// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackMyMacros.Persistance;

#nullable disable

namespace TrackMyMacros.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112075758_Mesocycle")]
    partial class Mesocycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.DailyLimit.DailyLimits", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeekdaysMealsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("WeekendMealsPerDay")
                        .HasColumnType("integer");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("DailyLimits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Calories = 2400,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 823, DateTimeKind.Utc).AddTicks(1949),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 823, DateTimeKind.Utc).AddTicks(1980),
                            WeekdaysMealsPerDay = 5,
                            WeekendMealsPerDay = 5,
                            WeightInKg = 75.900000000000006
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Day.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedCarbohydrate")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFat")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedProtein")
                        .HasColumnType("integer");

                    b.Property<double>("Carbohydrate")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<int>("MealCount")
                        .HasColumnType("integer");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b77ca66e-b3bf-4bf6-af79-6ef199bb3c1b"),
                            AllowedCarbohydrate = 100,
                            AllowedFat = 100,
                            AllowedProtein = 100,
                            Carbohydrate = 10.0,
                            Date = new DateOnly(2025, 1, 12),
                            Fat = 10.0,
                            MealCount = 1,
                            Protein = 10.0
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Exercise.BodyPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<Guid>("Id"), 50L, null, null, null, null, null);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2aa88079-b75d-417d-9eb2-6517fd2331c0"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8706),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8823),
                            Name = "Calves",
                            Size = 3.0
                        },
                        new
                        {
                            Id = new Guid("6610bfab-7248-4b7b-94cd-b9fd5e38290d"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8877),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8881),
                            Name = "Back",
                            Size = 4.0
                        },
                        new
                        {
                            Id = new Guid("e4232daf-15cc-40f3-ba6f-d29dc7e9ad2a"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8888),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8891),
                            Name = "Biceps",
                            Size = 1.0
                        },
                        new
                        {
                            Id = new Guid("6f639115-6ac7-48f9-8152-f08429bf7cd5"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8898),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8901),
                            Name = "Triceps",
                            Size = 3.0
                        },
                        new
                        {
                            Id = new Guid("8d68c9e3-f8b3-4d17-9446-1e188a1a4744"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8908),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8911),
                            Name = "Chest",
                            Size = 2.0
                        },
                        new
                        {
                            Id = new Guid("ec1f33a5-91e5-4de9-9b74-e0fe7255f883"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8920),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8924),
                            Name = "Abs",
                            Size = 2.0
                        },
                        new
                        {
                            Id = new Guid("5492de93-6f0b-443c-8f63-1eeb90b90c78"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8929),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8933),
                            Name = "Shoulders",
                            Size = 1.0
                        },
                        new
                        {
                            Id = new Guid("6dd13251-7a07-423d-920c-46fae6d2cdcc"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8940),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8943),
                            Name = "Hamstrings",
                            Size = 4.0
                        },
                        new
                        {
                            Id = new Guid("f87d2a54-ba1a-4dbc-a900-25531fdbfbeb"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8950),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8953),
                            Name = "Quads",
                            Size = 4.0
                        },
                        new
                        {
                            Id = new Guid("d0d8ea0f-c077-42be-b31f-14ed90353455"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(8998),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9002),
                            Name = "Glutes",
                            Size = 3.0
                        },
                        new
                        {
                            Id = new Guid("ae834296-64ec-421a-ab40-d4a93dbbbe9f"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9008),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9011),
                            Name = "Neck",
                            Size = 1.0
                        },
                        new
                        {
                            Id = new Guid("18b68da4-f760-45cb-97c3-a216bf7f99b3"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9017),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9021),
                            Name = "Forearms",
                            Size = 1.0
                        },
                        new
                        {
                            Id = new Guid("d2be7249-479c-40e6-960e-ed906cd8c919"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9028),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9031),
                            Name = "Traps",
                            Size = 3.0
                        },
                        new
                        {
                            Id = new Guid("fb70b309-fd97-4d65-8705-e4b4c490b653"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9037),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 822, DateTimeKind.Utc).AddTicks(9041),
                            Name = "Lower Back",
                            Size = 3.0
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Exercise.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<Guid>("Id"), 50L, null, null, null, null, null);

                    b.Property<Guid>("BodyPartId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BodyWeightExercise")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("8d68c9e3-f8b3-4d17-9446-1e188a1a4744"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9906),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9909),
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("c0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("f87d2a54-ba1a-4dbc-a900-25531fdbfbeb"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9933),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9936),
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("d0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("6dd13251-7a07-423d-920c-46fae6d2cdcc"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9952),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9955),
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("e0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("8d68c9e3-f8b3-4d17-9446-1e188a1a4744"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9970),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9973),
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("f0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("6610bfab-7248-4b7b-94cd-b9fd5e38290d"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9989),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 827, DateTimeKind.Utc).AddTicks(9992),
                            Name = "Pull Down"
                        },
                        new
                        {
                            Id = new Guid("a0d4b8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("ec1f33a5-91e5-4de9-9b74-e0fe7255f883"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(12),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(15),
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("a0d4a8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("f87d2a54-ba1a-4dbc-a900-25531fdbfbeb"),
                            BodyWeightExercise = true,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(29),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(32),
                            Name = "Reverse Nordics"
                        },
                        new
                        {
                            Id = new Guid("a0d4d8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("6610bfab-7248-4b7b-94cd-b9fd5e38290d"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(46),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(49),
                            Name = "DualCableRow"
                        },
                        new
                        {
                            Id = new Guid("a0d4e8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("8d68c9e3-f8b3-4d17-9446-1e188a1a4744"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(54),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(58),
                            Name = "RDL"
                        },
                        new
                        {
                            Id = new Guid("a0b4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("2aa88079-b75d-417d-9eb2-6517fd2331c0"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(74),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(77),
                            Name = "Calves Four Second Eccentric"
                        },
                        new
                        {
                            Id = new Guid("a0a4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("2aa88079-b75d-417d-9eb2-6517fd2331c0"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(90),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(93),
                            Name = "Calves Two Second Pause"
                        },
                        new
                        {
                            Id = new Guid("a0c4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("e4232daf-15cc-40f3-ba6f-d29dc7e9ad2a"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(106),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(109),
                            Name = "Lying Dumbell Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("a0e4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("6f639115-6ac7-48f9-8152-f08429bf7cd5"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(124),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(127),
                            Name = "Lying Overhead Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("a0f4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                            BodyPartId = new Guid("5492de93-6f0b-443c-8f63-1eeb90b90c78"),
                            BodyWeightExercise = false,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(177),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 828, DateTimeKind.Utc).AddTicks(180),
                            Name = "Single Arm Cable Lateral Raise"
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 100L, null, null, null, null, null);

                    b.Property<double>("CarbohydrateAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("DefaultQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("FatAmount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uuid");

                    b.Property<double?>("Max")
                        .HasColumnType("double precision");

                    b.Property<double?>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("ProteinAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantityInGrams")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("UomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarbohydrateAmount = 11.0,
                            FatAmount = 5.0,
                            Name = "Peanut Butter",
                            ProteinAmount = 20.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarbohydrateAmount = 40.0,
                            FatAmount = 8.0,
                            Name = "Hovis",
                            ProteinAmount = 10.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 3,
                            CarbohydrateAmount = 14.0,
                            FatAmount = 0.29999999999999999,
                            Name = "Apple",
                            ProteinAmount = 0.29999999999999999,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 4,
                            CarbohydrateAmount = 5.5,
                            FatAmount = 3.1000000000000001,
                            Name = "Arrabiata Sauce Barilla",
                            ProteinAmount = 1.3999999999999999,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 5,
                            CarbohydrateAmount = 4.0,
                            DefaultQuantity = 40.0,
                            FatAmount = 0.20000000000000001,
                            Name = "Arla Kvarg Vanilj",
                            ProteinAmount = 9.6999999999999993,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 6,
                            CarbohydrateAmount = 23.0,
                            FatAmount = 0.10000000000000001,
                            Name = "Banana",
                            ProteinAmount = 1.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 7,
                            CarbohydrateAmount = 52.0,
                            FatAmount = 0.10000000000000001,
                            Name = "Basmati Rice",
                            ProteinAmount = 5.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 8,
                            CarbohydrateAmount = 7.5999999999999996,
                            FatAmount = 0.5,
                            Name = "Blueberries",
                            ProteinAmount = 0.5,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 9,
                            CarbohydrateAmount = 65.0,
                            FatAmount = 2.2000000000000002,
                            Name = "Bran Flakes",
                            ProteinAmount = 11.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 10,
                            CarbohydrateAmount = 44.0,
                            DefaultQuantity = 80.0,
                            FatAmount = 4.0,
                            Name = "Bread",
                            ProteinAmount = 10.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 11,
                            CarbohydrateAmount = 0.40000000000000002,
                            FatAmount = 75.0,
                            Name = "Breggott",
                            ProteinAmount = 0.40000000000000002,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 12,
                            CarbohydrateAmount = 76.0,
                            FatAmount = 1.3,
                            Name = "Bulgur",
                            ProteinAmount = 12.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 13,
                            CarbohydrateAmount = 0.10000000000000001,
                            FatAmount = 0.10000000000000001,
                            Name = "Chicken Breast",
                            ProteinAmount = 23.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 14,
                            CarbohydrateAmount = 6.5,
                            DefaultQuantity = 255.0,
                            FatAmount = 1.5,
                            Name = "Chilli",
                            ProteinAmount = 7.7999999999999998,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 15,
                            CarbohydrateAmount = 26.0,
                            DefaultQuantity = 40.0,
                            FatAmount = 0.80000000000000004,
                            Name = "Weetabix",
                            ProteinAmount = 4.5,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 16,
                            CarbohydrateAmount = 3.1000000000000001,
                            DefaultQuantity = 170.0,
                            FatAmount = 1.5,
                            Name = "Milk",
                            ProteinAmount = 3.2999999999999998,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 17,
                            CarbohydrateAmount = 77.0,
                            FatAmount = 0.10000000000000001,
                            Name = "Raisins",
                            ProteinAmount = 2.5,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 18,
                            CarbohydrateAmount = 4.2999999999999998,
                            DefaultQuantity = 40.0,
                            FatAmount = 21.0,
                            Name = "Philadelphia",
                            ProteinAmount = 5.4000000000000004,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 19,
                            CarbohydrateAmount = 38.0,
                            FatAmount = 113.0,
                            Name = "Huel",
                            ProteinAmount = 29.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 20,
                            CarbohydrateAmount = 0.10000000000000001,
                            FatAmount = 0.10000000000000001,
                            Name = "Chicken Breast",
                            ProteinAmount = 23.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 21,
                            CarbohydrateAmount = 28.84,
                            FatAmount = 0.40000000000000002,
                            Name = "Bulgur Cooked",
                            ProteinAmount = 4.7999999999999998,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 22,
                            CarbohydrateAmount = 55.0,
                            FatAmount = 4.9000000000000004,
                            Name = "Tortilla",
                            ProteinAmount = 8.3000000000000007,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 23,
                            CarbohydrateAmount = 0.0,
                            FatAmount = 100.0,
                            Name = "Oil",
                            ProteinAmount = 0.0,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 24,
                            CarbohydrateAmount = 6.4000000000000004,
                            FatAmount = 0.5,
                            Name = "Frozen Strawberries",
                            ProteinAmount = 0.5,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 25,
                            CarbohydrateAmount = 50.0,
                            FatAmount = 15.0,
                            Name = "Granola",
                            ProteinAmount = 0.69999999999999996,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        },
                        new
                        {
                            Id = 26,
                            CarbohydrateAmount = 0.10000000000000001,
                            FatAmount = 32.0,
                            Name = "Kilmeaden",
                            ProteinAmount = 25.5,
                            Quantity = 100.0,
                            QuantityInGrams = 100,
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UomId = 1
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.FoodCombo.FoodCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodCombos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73150c63-5645-4d0a-abd6-e7657928117f"),
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 831, DateTimeKind.Utc).AddTicks(5819),
                            Name = "Test Food Combo"
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Mesocycle.Mesocycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<Guid>("Id"), 100L, null, null, null, null, null);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Mesocycles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 844, DateTimeKind.Utc).AddTicks(709),
                            Name = "Default Mesocycle"
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Recipe.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.WeightReading.WeightReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeightReadings");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Uom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Uoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 12, 7, 57, 57, 851, DateTimeKind.Utc).AddTicks(61),
                            LastModifiedDate = new DateTime(2025, 1, 12, 7, 57, 57, 851, DateTimeKind.Utc).AddTicks(122),
                            Name = "Grams"
                        });
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Day.Day", b =>
                {
                    b.OwnsMany("TrackMyMacros.Domain.ValueObjects.Meal", "Meals", b1 =>
                        {
                            b1.Property<Guid>("DayId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AllowedCarbohydrate")
                                .HasColumnType("integer");

                            b1.Property<int>("AllowedFat")
                                .HasColumnType("integer");

                            b1.Property<int>("AllowedProtein")
                                .HasColumnType("integer");

                            b1.Property<double>("Carbohydrate")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision");

                            b1.HasKey("DayId", "Id");

                            b1.ToTable("Meal");

                            b1.WithOwner()
                                .HasForeignKey("DayId");

                            b1.OwnsMany("TrackMyMacros.Domain.ValueObjects.FoodAmount", "FoodAmounts", b2 =>
                                {
                                    b2.Property<Guid>("MealDayId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MealId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("Carbohydrate")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Fat")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("FoodId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Protein")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Quantity")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MealDayId", "MealId", "Id");

                                    b2.ToTable("FoodAmount");

                                    b2.WithOwner()
                                        .HasForeignKey("MealDayId", "MealId");

                                    b2.HasData(
                                        new
                                        {
                                            MealDayId = new Guid("b77ca66e-b3bf-4bf6-af79-6ef199bb3c1b"),
                                            MealId = 1,
                                            Id = 1,
                                            Carbohydrate = 10.0,
                                            Fat = 10.0,
                                            FoodId = 3,
                                            Protein = 10.0,
                                            Quantity = 100.0
                                        });
                                });

                            b1.Navigation("FoodAmounts");

                            b1.HasData(
                                new
                                {
                                    DayId = new Guid("b77ca66e-b3bf-4bf6-af79-6ef199bb3c1b"),
                                    Id = 1,
                                    AllowedCarbohydrate = 10,
                                    AllowedFat = 10,
                                    AllowedProtein = 10,
                                    Carbohydrate = 10.0,
                                    Fat = 10.0,
                                    Protein = 10.0
                                });
                        });

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Exercise.Exercise", b =>
                {
                    b.HasOne("TrackMyMacros.Domain.Aggregates.Exercise.BodyPart", "BodyPart")
                        .WithMany()
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.FoodCombo.FoodCombo", b =>
                {
                    b.OwnsMany("TrackMyMacros.Domain.ValueObjects.FoodComboAmount", "FoodComboAmounts", b1 =>
                        {
                            b1.Property<Guid>("FoodComboId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Carbohydrate")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision");

                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodComboId", "Id");

                            b1.ToTable("FoodComboAmount");

                            b1.WithOwner()
                                .HasForeignKey("FoodComboId");

                            b1.HasData(
                                new
                                {
                                    FoodComboId = new Guid("73150c63-5645-4d0a-abd6-e7657928117f"),
                                    Id = 1,
                                    Carbohydrate = 10.0,
                                    Fat = 10.0,
                                    FoodId = 1,
                                    Protein = 10.0,
                                    Quantity = 40.0
                                },
                                new
                                {
                                    FoodComboId = new Guid("73150c63-5645-4d0a-abd6-e7657928117f"),
                                    Id = 2,
                                    Carbohydrate = 10.0,
                                    Fat = 10.0,
                                    FoodId = 2,
                                    Protein = 10.0,
                                    Quantity = 200.0
                                });
                        });

                    b.Navigation("FoodComboAmounts");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Mesocycle.Mesocycle", b =>
                {
                    b.OwnsMany("TrackMyMacros.Domain.Aggregates.Mesocycle.MesocycleWeek", "MesocycleWeeks", b1 =>
                        {
                            b1.Property<Guid>("MesocycleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("WeekIndex")
                                .HasColumnType("integer");

                            b1.HasKey("MesocycleId", "Id");

                            b1.ToTable("MesocycleWeek");

                            b1.WithOwner()
                                .HasForeignKey("MesocycleId");

                            b1.OwnsMany("TrackMyMacros.Domain.Aggregates.Mesocycle.MesocycleWeekDay", "MesocycleWeekDays", b2 =>
                                {
                                    b2.Property<Guid>("MesocycleWeekMesocycleId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MesocycleWeekId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("Complete")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer");

                                    b2.HasKey("MesocycleWeekMesocycleId", "MesocycleWeekId", "Id");

                                    b2.ToTable("MesocycleWeekDay");

                                    b2.WithOwner()
                                        .HasForeignKey("MesocycleWeekMesocycleId", "MesocycleWeekId");

                                    b2.OwnsMany("TrackMyMacros.Domain.Aggregates.Mesocycle.ExerciseDaySet", "ExerciseDaySets", b3 =>
                                        {
                                            b3.Property<Guid>("MesocycleWeekDayMesocycleWeekMesocycleId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("MesocycleWeekDayMesocycleWeekId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("MesocycleWeekDayId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<Guid>("ExerciseId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("Reps")
                                                .HasColumnType("integer");

                                            b3.Property<int>("TargetReps")
                                                .HasColumnType("integer");

                                            b3.Property<double>("TargetWeight")
                                                .HasColumnType("double precision");

                                            b3.HasKey("MesocycleWeekDayMesocycleWeekMesocycleId", "MesocycleWeekDayMesocycleWeekId", "MesocycleWeekDayId", "Id");

                                            b3.ToTable("ExerciseDaySet");

                                            b3.WithOwner()
                                                .HasForeignKey("MesocycleWeekDayMesocycleWeekMesocycleId", "MesocycleWeekDayMesocycleWeekId", "MesocycleWeekDayId");

                                            b3.HasData(
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 1,
                                                    ExerciseId = new Guid("e0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 14,
                                                    TargetWeight = 20.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 2,
                                                    ExerciseId = new Guid("f0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 12,
                                                    TargetWeight = 49.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 3,
                                                    ExerciseId = new Guid("c0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 8,
                                                    TargetWeight = 5.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 4,
                                                    ExerciseId = new Guid("a0a4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 40.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 5,
                                                    ExerciseId = new Guid("a0c4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 8,
                                                    TargetWeight = 9.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 6,
                                                    ExerciseId = new Guid("a0e4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 17.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 7,
                                                    ExerciseId = new Guid("a0d4a8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 3,
                                                    TargetWeight = 100.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 8,
                                                    ExerciseId = new Guid("a0f4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 7,
                                                    TargetWeight = 15.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 1,
                                                    Id = 9,
                                                    ExerciseId = new Guid("a0d4b8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 5,
                                                    TargetWeight = 10.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 10,
                                                    ExerciseId = new Guid("e0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 14,
                                                    TargetWeight = 20.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 11,
                                                    ExerciseId = new Guid("a0d4d8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 46.5
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 12,
                                                    ExerciseId = new Guid("a0d4e8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 9,
                                                    TargetWeight = 45.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 13,
                                                    ExerciseId = new Guid("a0b4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 8,
                                                    TargetWeight = 41.5
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 14,
                                                    ExerciseId = new Guid("a0c4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 8,
                                                    TargetWeight = 9.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 15,
                                                    ExerciseId = new Guid("a0e4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 17.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 16,
                                                    ExerciseId = new Guid("a0d4a8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 3,
                                                    TargetWeight = 100.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 17,
                                                    ExerciseId = new Guid("a0f4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 7,
                                                    TargetWeight = 15.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 2,
                                                    Id = 18,
                                                    ExerciseId = new Guid("a0d4b8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 5,
                                                    TargetWeight = 10.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 19,
                                                    ExerciseId = new Guid("b0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 15,
                                                    TargetWeight = 16.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 20,
                                                    ExerciseId = new Guid("f0d4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 12,
                                                    TargetWeight = 49.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 21,
                                                    ExerciseId = new Guid("a0d4e8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 9,
                                                    TargetWeight = 45.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 22,
                                                    ExerciseId = new Guid("a0a4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 40.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 23,
                                                    ExerciseId = new Guid("a0c4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 8,
                                                    TargetWeight = 9.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 24,
                                                    ExerciseId = new Guid("a0e4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 10,
                                                    TargetWeight = 17.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 25,
                                                    ExerciseId = new Guid("a0d4a8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 3,
                                                    TargetWeight = 100.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 26,
                                                    ExerciseId = new Guid("a0f4c8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 7,
                                                    TargetWeight = 15.0
                                                },
                                                new
                                                {
                                                    MesocycleWeekDayMesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                                    MesocycleWeekDayMesocycleWeekId = 1,
                                                    MesocycleWeekDayId = 3,
                                                    Id = 27,
                                                    ExerciseId = new Guid("a0d4b8cd-e49a-49ca-88a5-2348fdc79f6d"),
                                                    Reps = 0,
                                                    TargetReps = 5,
                                                    TargetWeight = 10.0
                                                });
                                        });

                                    b2.Navigation("ExerciseDaySets");

                                    b2.HasData(
                                        new
                                        {
                                            MesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                            MesocycleWeekId = 1,
                                            Id = 1,
                                            Complete = false,
                                            DayOfWeek = 1
                                        },
                                        new
                                        {
                                            MesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                            MesocycleWeekId = 1,
                                            Id = 2,
                                            Complete = false,
                                            DayOfWeek = 3
                                        },
                                        new
                                        {
                                            MesocycleWeekMesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                            MesocycleWeekId = 1,
                                            Id = 3,
                                            Complete = false,
                                            DayOfWeek = 5
                                        });
                                });

                            b1.Navigation("MesocycleWeekDays");

                            b1.HasData(
                                new
                                {
                                    MesocycleId = new Guid("29913df7-6236-48c5-bb48-3d32fd1bb4d5"),
                                    Id = 1,
                                    WeekIndex = 1
                                });
                        });

                    b.Navigation("MesocycleWeeks");
                });

            modelBuilder.Entity("TrackMyMacros.Domain.Aggregates.Recipe.Recipe", b =>
                {
                    b.OwnsMany("TrackMyMacros.Domain.ValueObjects.RecipeFoodAmount", "RecipeFoodAmounts", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Carbohydrate")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision");

                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeFoodAmount");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("RecipeFoodAmounts");
                });
#pragma warning restore 612, 618
        }
    }
}
